
DROP DATABASE IF EXISTS RabbitsDB
GO

CREATE DATABASE RabbitsDB
GO

USE RabbitsDB
GO

DROP TABLE IF EXISTS Rabbits
GO

CREATE TABLE Rabbits (
	RabbitID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	RabbitName VARCHAR(50) NULL,
	RabbitAge INT NULL
)

INSERT INTO Rabbits VALUES('Jack', 1)
INSERT INTO Rabbits VALUES('Jill', 3)
INSERT INTO Rabbits VALUES('Bob', 2)

SELECT * FROM Rabbits